[environment]
cpu_count = 10
exec_env = "posix"
free_mem = 9.5
overcommit_policy = "n/a"
overcommit_limit = "n/a"
nipype_version = "1.10.0"
templateflow_version = "24.2.2"
version = "25.1.0.dev19+gc1afa7a6.d20250502"

[execution]
bids_dir = "/Users/martinnorgaard/Documents/GitHub/fmriprep/fmriprep/data/tests/pet"
bids_database_dir = "/Users/martinnorgaard/Dropbox/Mac/Documents/GitHub/fmriprep/work/20250502-134958_6c1c333c-9d45-4f6e-95e0-49db32648158/bids_db"
boilerplate_only = false
sloppy = false
debug = []
petprep_dir = "/Users/martinnorgaard/Documents/GitHub/fmriprep/fmriprep/data/tests/pet/derivatives"
fs_license_file = "/Applications/freesurfer/7.4.1/license.txt"
fs_subjects_dir = "/Users/martinnorgaard/Documents/GitHub/fmriprep/fmriprep/data/tests/pet/derivatives/sourcedata/freesurfer"
layout = "BIDS Layout: ...riprep/fmriprep/data/tests/pet | Subjects: 1 | Sessions: 1 | Runs: 0"
log_dir = "/Users/martinnorgaard/Documents/GitHub/fmriprep/fmriprep/data/tests/pet/derivatives/logs"
log_level = 25
low_mem = false
md_only_boilerplate = false
notrack = true
track_carbon = false
country_code = "CAN"
output_dir = "/Users/martinnorgaard/Documents/GitHub/fmriprep/fmriprep/data/tests/pet/derivatives"
aggr_ses_reports = 4
output_layout = "bids"
output_spaces = "MNI152NLin2009cAsym:res-native"
reports_only = false
run_uuid = "20250502-134958_6c1c333c-9d45-4f6e-95e0-49db32648158"
participant_label = [ "01",]
templateflow_home = "/Users/martinnorgaard/.cache/templateflow"
work_dir = "/Users/martinnorgaard/Dropbox/Mac/Documents/GitHub/fmriprep/work"
write_graph = false

[workflow]
anat_only = false
bold2anat_dof = 6
bold2anat_init = "auto"
cifti_output = false
hires = true
fs_no_resume = false
ignore = []
force = []
level = "full"
longitudinal = false
run_msmsulc = true
medial_surface_nan = false
project_goodvoxels = false
regressors_all_comps = false
regressors_dvars_th = 1.5
regressors_fd_th = 0.5
run_reconall = true
skull_strip_fixed_seed = false
skull_strip_template = "OASIS30ANTs"
skull_strip_t1w = "force"

[nipype]
crashfile_format = "txt"
get_linked_libs = false
nprocs = 10
omp_nthreads = 8
plugin = "MultiProc"
remove_unnecessary_outputs = true
resource_monitor = false
stop_on_first_crash = false

[seeds]
master = 52684
ants = 52403
numpy = 50580

[execution.derivatives]

[execution.dataset_links]
raw = "/Users/martinnorgaard/Documents/GitHub/fmriprep/fmriprep/data/tests/pet"
templateflow = "/Users/martinnorgaard/.cache/templateflow"

[nipype.plugin_args]
maxtasksperchild = 1
raise_insufficient = false
