[environment]
cpu_count = 10
exec_env = "posix"
free_mem = 1.7
overcommit_policy = "n/a"
overcommit_limit = "n/a"
nipype_version = "1.8.6"
templateflow_version = "23.0.0"
version = "0+unknown"

[execution]
bids_dir = "/Users/martinnorgaard/Documents/dev_dir2/nimh_cox_test"
bids_database_dir = "/Users/martinnorgaard/Dropbox/Mac/Documents/GitHub/petprep/work/20230501-103826_381ae982-54a1-4fd1-b9e0-a3c8f6f61f4f/bids_db"
boilerplate_only = false
sloppy = false
debug = []
petprep_dir = "/Users/martinnorgaard/Documents/dev_dir2/nimh_cox_test/derivatives"
fs_license_file = "/Applications/freesurfer/dev/license.txt"
fs_subjects_dir = "/Users/martinnorgaard/Documents/dev_dir2/nimh_cox_test/derivatives/sourcedata/freesurfer"
layout = "BIDS Layout: ...cuments/dev_dir2/nimh_cox_test | Subjects: 1 | Sessions: 2 | Runs: 0"
log_dir = "/Users/martinnorgaard/Documents/dev_dir2/nimh_cox_test/derivatives/logs"
log_level = 25
low_mem = false
md_only_boilerplate = false
notrack = true
track_carbon = false
country_code = "CAN"
output_dir = "/Users/martinnorgaard/Documents/dev_dir2/nimh_cox_test/derivatives"
output_layout = "bids"
output_spaces = "MNI152NLin2009cAsym:res-native"
reports_only = false
run_uuid = "20230501-103826_381ae982-54a1-4fd1-b9e0-a3c8f6f61f4f"
participant_label = [ "PS11",]
templateflow_home = "/Users/martinnorgaard/.cache/templateflow"
work_dir = "/Users/martinnorgaard/Dropbox/Mac/Documents/GitHub/petprep/work"
write_graph = false

[workflow]
anat_only = false
pet2t1w_init = "register"
cifti_output = false
hires = true
ignore = []
longitudinal = false
medial_surface_nan = false
project_goodvoxels = false
regressors_dvars_th = 1.5
regressors_fd_th = 0.5
run_reconall = true
skull_strip_fixed_seed = false
skull_strip_template = "OASIS30ANTs"
skull_strip_t1w = "force"

[nipype]
crashfile_format = "txt"
get_linked_libs = false
nprocs = 10
omp_nthreads = 8
plugin = "MultiProc"
resource_monitor = false
stop_on_first_crash = false

[seeds]
master = 45427
ants = 8735
numpy = 59801

[nipype.plugin_args]
maxtasksperchild = 1
raise_insufficient = false
