name: Code Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        auto-activate-base: true
        
    - name: Install dependencies
      run: |
        conda env create -f environment.yml
        pip install -e .

    - name: Run tests with coverage
      run: |
        coverage run --source=petprep -m pytest
        coverage html

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: htmlcov
        path: htmlcov

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
