name: Code Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage pytest petprep

    - name: Run tests with coverage
      run: |
        coverage run --source=petprep -m pytest
        coverage html

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: htmlcov
        path: htmlcov

    - name: Upload coverage to Codecov
      run: |
        codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}